### ISSUE TITLE
When I click on blob URL I cannot access the file

### ISSUE THREAD

**Issue by melohagan** [chungchunwang/Budibase-File-Repeater#2]
I have successfully used the File Upload Component to upload to a text field as follows:

```json
.[{"name":"yellow.jpg","type":"image/jpeg","size":83667,"link":"data:image/jpeg;base64,/9j/4AAQ ... ... ... B5Tdqca+W/l18J5eNr//Z"}].
```

However when I click on the blob URL, I just get redirected without seeing the file:

![tour](https://user-images.githubusercontent.com/101575380/206125434-0985b392-4a6a-477e-8b15-e37592653907.gif)

<img width="245" alt="Screenshot 2022-12-07 at 08 19 46" src="https://user-images.githubusercontent.com/101575380/206125637-e983e27d-f2fe-4be0-bb2e-fda8d10a628a.png">
<img width="245" alt="Screenshot 2022-12-07 at 08 20 16" src="https://user-images.githubusercontent.com/101575380/206125727-e8a9162e-1bc3-44e0-8246-19ab03444b76.png">

**EDIT**
Using a data URL in an Image component works wonderfully 😄 
<img width="1177" alt="Screenshot 2022-12-07 at 08 22 21" src="https://user-images.githubusercontent.com/101575380/206126159-7eeacb4b-2f0a-4619-bbdc-dc280ce1a2fc.png">

**Comment by chungchunwang** [comment]
Hi! This is odd, as the browser doesn't seem to attempt to go to the link at all, it just jumps back to the main page. Is the blobURL inserted into the URL attribute of the link component? Also, does the blob URL work when it is manually copied into a new tab? Additionally, does clicking on a file inside the file upload plugin work? (It also works using blobURL)

**Comment by melohagan** [comment]
Hey @chungchunwang 

The URL does work when manually copied. Appears to be a little quirk with the link component. Closing!
