### ISSUE TITLE
Unable to view files

### ISSUE THREAD

**Issue by apparentlyjeff** [chungchunwang/Budibase-File-Repeater#5]
I've set up the file uploader and it works fine and displays the attachments I've uploaded when editing through the form.  But when placing this component into my budibase app, it just remains blank.  I see no file name and no indication of any attachment whatsoever.
If I change the data in the underlying field, the component does display a JS error, so it's reading the data, but for some reason it's not displaying anything.

**Comment by chungchunwang** [comment]
Hi! Could you please provide me with a few screenshots of the issue? It would better help me diagnose this.
A few fixes I can think of are:
- Make sure that the components inside the repeater are displaying the context provided by the repeater.
- Make sure that the Encoding Protection feature is set to the same setting for both the file uploader and repeater.

**Comment by apparentlyjeff** [comment]
Form to upload attachments.  Seems to work...
![image](https://user-images.githubusercontent.com/15859008/226177668-3c0a43ff-0be0-46ea-829e-83dd36ecbcc1.png)
![image](https://user-images.githubusercontent.com/15859008/226177992-02a5191f-5aa1-48e6-a637-86ca5a8e792d.png)

Page to display results and attachments.  I added a paragraph that displays the attachment field to be sure data was getting through. 
![image](https://user-images.githubusercontent.com/15859008/226177749-429ddfd9-67d4-4e60-a276-71731359c7c6.png)
![image](https://user-images.githubusercontent.com/15859008/226178179-188a5129-19a1-4dc5-9a59-b79ce631d279.png)

And I've manually editted the data stored in the field, which results in the output displaying an error, so I know it's reading the data.
![image](https://user-images.githubusercontent.com/15859008/226178086-947cbb63-2421-43c3-80a0-eca612997ceb.png)

**Comment by chungchunwang** [comment]
Hi! This plugin works a bit like Budibase's [Repeater](https://docs.budibase.com/docs/repeater) component. Given data for a particular file field, it merely repeats its children for each file in the field. It is up to the children of the repeater component to display the data. The children of the file repeater component gain access to the additional fields: data URL, blob URL, name, size, type properties.

See the third image of the [How To Use section](https://github.com/chungchunwang/Budibase-File-Repeater#how-to-use) for an example of this.

**Comment by chungchunwang** [comment]
What you would need to do here is to add a Link component as a child of the File Repeater component. Then set the name property of the Link component to the name of the file (provided as a binding by the File Repeater), and the URL component to the blob URL of the file (also provided as a binding).

**Comment by chungchunwang** [comment]
The [How To Use section](https://github.com/chungchunwang/Budibase-File-Repeater#how-to-use) gives a pretty good walkthrough of how to use the component. Try checking it out!

**Comment by apparentlyjeff** [comment]
Thanks.  I'm obviously dense.  I thought I read the instructions, and now what you've said makes perfect sense.
